version: '3.5'

services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    container_name: postgres-demo
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '${POSTGRES_PORT:-5432}:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker-postgres
    env_file:
      - .env
    ports:
      - '${APP_PORT:-4005}:4005'
    depends_on:
      - db
    volumes:
      - ./src:/app/src

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4-demo
    env_file:
      - .env
    ports:
      - '${PGADMIN_PORT:-5050}:80'
    depends_on:
      - db
